# Generated by Django 6.1 on 2026-09-07 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('obras', '0001_initial'),
        ('productos', '0002_proveedor_productoproveedor_producto_proveedores_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('RESERVADO', 'Reservado'), ('ACTIVO', 'Activo'), ('PENDIENTE', 'Pendiente'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='RESERVADO', max_length=30)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observacion', models.CharField(blank=True, max_length=400)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='clientes.cliente')),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos', to='obras.obra')),
            ],
            options={
                'db_table': 'prestamos',
                'ordering': ['-fecha_reserva', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PrestamoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='prestamos.prestamo')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_prestamo', to='productos.producto')),
            ],
            options={
                'db_table': 'prestamo_detalles',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(fields=['cliente', 'estado'], name='prestamos_cliente_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(fields=['estado'], name='prestamos_estado_idx'),
        ),
    ]
