# Generated by Django 6.1 on 2026-09-11 07:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0002_proveedor_productoproveedor_producto_proveedores_and_more'),
        ('transportadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_entrega_programada', models.DateField()),
                ('fecha_entrega_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RESERVADA', 'Reservada'), ('ENTREGADA', 'Entregada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15)),
                ('prioridad', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remisiones', to='clientes.cliente')),
                ('transportador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remisiones', to='transportadores.transportador')),
            ],
            options={
                'db_table': 'remisiones',
                'ordering': ['-fecha_emision', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RemisionAlarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('prioridad', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=15)),
                ('descripcion', models.TextField()),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RESUELTA', 'Resuelta'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15)),
                ('resuelta_at', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('remision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarmas', to='remisiones.remision')),
            ],
            options={
                'db_table': 'remision_alarmas',
                'ordering': ['estado', 'fecha_limite', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RemisionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('unidad_medida', models.CharField(blank=True, max_length=30)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=14)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_remision', to='productos.producto')),
                ('remision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='remisiones.remision')),
            ],
            options={
                'db_table': 'remision_detalles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RemisionReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(default=django.utils.timezone.localdate)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('confirmada_at', models.DateTimeField(blank=True, null=True)),
                ('cancelada_at', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('remision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='remisiones.remision')),
            ],
            options={
                'db_table': 'remision_reservas',
                'ordering': ['-fecha_reserva', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='remision',
            index=models.Index(fields=['cliente'], name='remisiones_cliente_idx'),
        ),
        migrations.AddIndex(
            model_name='remision',
            index=models.Index(fields=['estado', 'fecha_entrega_programada'], name='remisiones_estado_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='remisionalarma',
            index=models.Index(fields=['estado', 'fecha_limite'], name='alarmas_estado_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='remisiondetalle',
            index=models.Index(fields=['producto'], name='remision_detalle_producto_idx'),
        ),
        migrations.AddConstraint(
            model_name='remisiondetalle',
            constraint=models.UniqueConstraint(fields=('remision', 'producto'), name='remision_producto_unico'),
        ),
        migrations.AddConstraint(
            model_name='remisiondetalle',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='remision_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='remisiondetalle',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='remision_precio_no_negativo'),
        ),
    ]
