# Generated by Django 6.1 on 2026-09-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remisiones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remision",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("CONFIRMADA", "Confirmada"),
                    ("RESERVADA", "Reservada"),
                    ("ENTREGADA", "Entregada"),
                    ("CANCELADA", "Cancelada"),
                ],
                default="PENDIENTE",
                max_length=15,
            ),
        ),
        migrations.AddConstraint(
            model_name="remisionreserva",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado__in", ["PENDIENTE", "CONFIRMADA"])),
                fields=("remision",),
                name="remision_reserva_activa_unica",
            ),
        ),
    ]
