# Generated by Django 6.1

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=27, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=150)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'responsables',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='responsable',
            index=models.Index(fields=['estado'], name='responsable_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='responsable',
            index=models.Index(fields=['apellido', 'nombre'], name='responsable_nombre_idx'),
        ),
    ]
