# Generated by Django 6.1 on 2026-09-07 22:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0002_proveedor_productoproveedor_producto_proveedores_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KardexMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VENTA', 'Venta'), ('PRESTAMO', 'Préstamo'), ('DEVOLUCION', 'Devolución'), ('PAGO', 'Pago'), ('REPOSICION', 'Reposición')], max_length=15)),
                ('numero_documento', models.CharField(blank=True, max_length=50)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(default='ACTIVO', max_length=30)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_kardex', to='clientes.cliente')),
            ],
            options={
                'db_table': 'kardex_movimientos',
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KardexDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_kardex', to='productos.producto')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='kardex.kardexmovimiento')),
            ],
            options={
                'db_table': 'kardex_detalles',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='kardexmovimiento',
            index=models.Index(fields=['cliente', 'fecha'], name='kardex_cliente_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='kardexmovimiento',
            index=models.Index(fields=['tipo'], name='kardex_tipo_idx'),
        ),
    ]
