# Generated by Django 6.1 on 2026-09-07 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('kardex', '0001_initial'),
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kardexmovimiento',
            name='obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_kardex', to='obras.obra'),
        ),
        migrations.AddIndex(
            model_name='kardexmovimiento',
            index=models.Index(fields=['obra'], name='kardex_obra_idx'),
        ),
    ]
