# Generated by Django 6.1 on 2026-09-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0002_kardexmovimiento_obra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kardexdetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
    ]
