# Generated by Django 6.1 on 2026-09-11 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0003_alter_kardexdetalle_cantidad'),
        ('remisiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kardexmovimiento',
            name='remision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_kardex', to='remisiones.remision'),
        ),
    ]
