# Generated by Django 6.1 on 2026-09-13 18:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_proveedor_productoproveedor_producto_proveedores_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existencia', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='productos.producto')),
            ],
            options={
                'db_table': 'inventario',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_entrega_programada', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra_creadas', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='productos.proveedor')),
            ],
            options={
                'db_table': 'ordenes_compra',
                'ordering': ['-fecha_emision', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('fecha_entrada', models.DateField(default=django.utils.timezone.localdate)),
                ('numero_factura', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='productos.proveedor')),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='orden_compra.ordencompra')),
            ],
            options={
                'db_table': 'entradas',
                'ordering': ['-fecha_entrada', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=14)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cantidad_recibida', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='orden_compra.ordencompra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_orden_compra', to='productos.producto')),
            ],
            options={
                'db_table': 'orden_compra_detalles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EntradaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=14)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('lote', models.CharField(blank=True, max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='orden_compra.entrada')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_entrada', to='productos.producto')),
            ],
            options={
                'db_table': 'entrada_detalles',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('entrada', 'producto'), name='entrada_producto_unico'), models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='entrada_cantidad_positiva'), models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='entrada_precio_no_negativo')],
            },
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['proveedor'], name='orden_compra_proveedor_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['estado', 'fecha_entrega_programada'], name='orden_compra_estado_fecha_idx'),
        ),
        migrations.AddConstraint(
            model_name='ordencompradetalle',
            constraint=models.UniqueConstraint(fields=('orden_compra', 'producto'), name='orden_compra_producto_unico'),
        ),
        migrations.AddConstraint(
            model_name='ordencompradetalle',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='orden_compra_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='ordencompradetalle',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='orden_compra_precio_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='ordencompradetalle',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_recibida__gte', 0)), name='orden_compra_recibida_no_negativa'),
        ),
    ]
