# Generated by Django 6.1 on 2026-09-14 05:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
        ("orden_compra", "0001_initial"),
        ("productos", "0002_proveedor_productoproveedor_producto_proveedores_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Salida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(blank=True, max_length=30, unique=True)),
                ("fecha", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("VENTA", "Venta"),
                            ("DEVOLUCION", "Devolución"),
                            ("TRASLADO", "Traslado"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("COMPLETADA", "Completada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "impuestos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="salidas",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="salidas_responsable",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "salidas",
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SalidaDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=3, max_digits=14)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "iva_linea",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_linea",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_salida",
                        to="productos.producto",
                    ),
                ),
                (
                    "salida",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="orden_compra.salida",
                    ),
                ),
            ],
            options={
                "db_table": "salida_detalles",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Lote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=100)),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                (
                    "cantidad_disponible",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lotes",
                        to="productos.producto",
                    ),
                ),
            ],
            options={
                "db_table": "lotes",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("producto", "codigo"), name="lote_producto_codigo_unico"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("cantidad_disponible__gte", 0)),
                        name="lote_cantidad_no_negativa",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MovimientoInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Entrada"),
                            ("SALIDA", "Salida"),
                            ("DEVOLUCION", "Devolución"),
                            ("AJUSTE", "Ajuste"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=3, max_digits=14)),
                ("referencia_tipo", models.CharField(blank=True, max_length=30)),
                (
                    "referencia_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("lote", models.CharField(blank=True, max_length=100)),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_inventario",
                        to="productos.producto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "movimientos_inventario",
                "ordering": ["-fecha", "-id"],
                "indexes": [
                    models.Index(
                        fields=["producto", "fecha"], name="mov_inv_producto_fecha_idx"
                    ),
                    models.Index(
                        fields=["referencia_tipo", "referencia_id"],
                        name="mov_inv_referencia_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="salida",
            index=models.Index(fields=["cliente"], name="salida_cliente_idx"),
        ),
        migrations.AddIndex(
            model_name="salida",
            index=models.Index(
                fields=["estado", "fecha"], name="salida_estado_fecha_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="salidadetalle",
            constraint=models.UniqueConstraint(
                fields=("salida", "producto"), name="salida_producto_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="salidadetalle",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad__gt", 0)), name="salida_cantidad_positiva"
            ),
        ),
        migrations.AddConstraint(
            model_name="salidadetalle",
            constraint=models.CheckConstraint(
                condition=models.Q(("precio_unitario__gte", 0)),
                name="salida_precio_no_negativo",
            ),
        ),
    ]
