# Generated by Django 6.1 on 2026-09-02

from django.db import migrations, models
import django.db.models.deletion


def cargar_tipos_producto(apps, schema_editor):
    TipoProducto = apps.get_model('productos', 'TipoProducto')
    TipoProducto.objects.bulk_create([
        TipoProducto(nombre='Andamios'),
        TipoProducto(nombre='Encofrado'),
    ])


def eliminar_tipos_producto(apps, schema_editor):
    TipoProducto = apps.get_model('productos', 'TipoProducto')
    TipoProducto.objects.filter(nombre__in=['Andamios', 'Encofrado']).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Producto',
                'verbose_name_plural': 'Tipos de Producto',
                'db_table': 'tipo_producto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('peso_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_alquiler', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_reposicion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('manual', models.FileField(blank=True, null=True, upload_to='productos/manuales/')),
                ('ficha_tecnica', models.FileField(blank=True, null=True, upload_to='productos/fichas_tecnicas/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='productos.tipoproducto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['descripcion'],
            },
        ),
        migrations.RunPython(cargar_tipos_producto, eliminar_tipos_producto),
    ]