# Generated by Django 6.1 on 2026-09-04 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nit', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'proveedor',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_subarriendo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vinculo_habilitado', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores_relacion', to='productos.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_relacion', to='productos.proveedor')),
            ],
            options={
                'db_table': 'producto_proveedor',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedores',
            field=models.ManyToManyField(related_name='productos', through='productos.ProductoProveedor', to='productos.proveedor'),
        ),
        migrations.AddConstraint(
            model_name='productoproveedor',
            constraint=models.UniqueConstraint(fields=('producto', 'proveedor'), name='producto_proveedor_unico'),
        ),
    ]
