# Generated by Django 6.1 on 2026-09-07 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=27, unique=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=20)),
                ('razon_social', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('ciudad', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('celular', models.CharField(max_length=20)),
                ('habilitado', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['razon_social'],
                'indexes': [models.Index(fields=['razon_social'], name='clientes_razon_social_idx'), models.Index(fields=['habilitado'], name='clientes_habilitado_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClienteDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('rut', 'RUT'), ('cedula_repr', 'Cédula del representante'), ('contrato_alquiler', 'Contrato de alquiler'), ('camara_comercio', 'Cámara de comercio'), ('certificado_bancario', 'Certificado bancario')], max_length=30)),
                ('archivo', models.FileField(upload_to='clientes/documentos/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Documento del cliente',
                'verbose_name_plural': 'Documentos de clientes',
                'db_table': 'cliente_documentos',
                'ordering': ['tipo'],
                'constraints': [models.UniqueConstraint(fields=('cliente', 'tipo'), name='cliente_documento_tipo_unico')],
            },
        ),
    ]
