# Generated by Django 6.1 on 2026-09-13 21:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0002_proveedor_productoproveedor_producto_proveedores_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cotizaciones',
                'ordering': ['-fecha_emision', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=14)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cotizaciones.cotizacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_cotizacion', to='productos.producto')),
            ],
            options={
                'db_table': 'cotizacion_detalles',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['cliente'], name='cotizacion_cliente_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['fecha_emision'], name='cotizacion_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['estado'], name='cotizacion_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='cotizacion',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_vencimiento__gte', models.F('fecha_emision'))), name='cotizacion_fecha_valida'),
        ),
        migrations.AddIndex(
            model_name='cotizaciondetalle',
            index=models.Index(fields=['cotizacion'], name='cotizacion_detalle_cot_idx'),
        ),
        migrations.AddConstraint(
            model_name='cotizaciondetalle',
            constraint=models.UniqueConstraint(fields=('cotizacion', 'producto'), name='cotizacion_producto_unico'),
        ),
        migrations.AddConstraint(
            model_name='cotizaciondetalle',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='cotizacion_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='cotizaciondetalle',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='cotizacion_precio_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='cotizaciondetalle',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='cotizacion_subtotal_no_negativo'),
        ),
    ]
