# Generated by Django 6.1 on 2026-09-14 04:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
        ("cotizaciones", "0001_initial"),
        ("productos", "0002_proveedor_productoproveedor_producto_proveedores_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cotizacion",
            name="cotizacion_fecha_valida",
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="vigencia_dias",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="cotizaciondetalle",
            name="iva_linea",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="cotizaciondetalle",
            name="total_linea",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("APROBADA", "Aprobada"),
                    ("RECHAZADA", "Rechazada"),
                    ("VENCIDA", "Vencida"),
                    ("CANCELADA", "Cancelada"),
                    ("CONVERTIDA", "Convertida"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="fecha_vencimiento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="cotizacion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("fecha_vencimiento__isnull", True),
                    ("fecha_vencimiento__gte", models.F("fecha_emision")),
                    _connector="OR",
                ),
                name="cotizacion_fecha_valida",
            ),
        ),
        migrations.AddConstraint(
            model_name="cotizacion",
            constraint=models.CheckConstraint(
                condition=models.Q(("vigencia_dias__gt", 0)),
                name="cotizacion_vigencia_positiva",
            ),
        ),
        migrations.AddConstraint(
            model_name="cotizaciondetalle",
            constraint=models.CheckConstraint(
                condition=models.Q(("iva_linea__gte", 0)),
                name="cotizacion_iva_no_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="cotizaciondetalle",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_linea__gte", 0)),
                name="cotizacion_total_linea_no_negativo",
            ),
        ),
    ]
