# Generated by Django 6.1 on 2026-09-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transportador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('documento', models.CharField(max_length=30, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('placa', models.CharField(blank=True, max_length=20)),
                ('habilitado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'transportadores',
                'ordering': ['nombre'],
            },
        ),
    ]
