# Generated by Django 6.1 on 2026-09-11 07:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def poblar_codigos_transportadores(apps, schema_editor):
    transportador_model = apps.get_model('transportadores', 'Transportador')
    for indice, transportador in enumerate(
        transportador_model.objects.order_by('id'),
        start=1,
    ):
        transportador.codigo = f'TR{indice:03d}'
        transportador.save(update_fields=['codigo'])


class Migration(migrations.Migration):

    dependencies = [
        ('remisiones', '0001_initial'),
        ('transportadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportadorVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_principal', models.BooleanField(default=False)),
                ('fecha_asignacion', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_desasignacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transportador_vehiculos',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=15, unique=True)),
                ('tipo', models.CharField(choices=[('CAMION', 'Camión'), ('FURGON', 'Furgón'), ('CAMIONETA', 'Camioneta')], max_length=30)),
                ('marca', models.CharField(blank=True, max_length=80)),
                ('modelo', models.CharField(blank=True, max_length=80)),
                ('capacidad_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('MANTENIMIENTO', 'Mantenimiento')], default='ACTIVO', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vehiculos',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=30, unique=True)),
                ('origen', models.CharField(blank=True, max_length=150)),
                ('destino', models.CharField(max_length=150)),
                ('pais_destino', models.CharField(default='Colombia', max_length=100)),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada_estimada', models.DateTimeField(blank=True, null=True)),
                ('fecha_llegada_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_CURSO', 'En curso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'viajes',
                'ordering': ['-fecha_salida', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ViajeRemision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_entrega', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CARGADA', 'Cargada'), ('ENTREGADA', 'Entregada'), ('DEVUELTA', 'Devuelta')], default='PENDIENTE', max_length=20)),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'viaje_remisiones',
            },
        ),
        migrations.RemoveField(
            model_name='transportador',
            name='habilitado',
        ),
        migrations.RemoveField(
            model_name='transportador',
            name='placa',
        ),
        migrations.AddField(
            model_name='transportador',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transportador',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(
            poblar_codigos_transportadores,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='transportador',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='transportador',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportador',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='transportador',
            name='licencia_categoria',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='transportador',
            name='licencia_numero',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transportador',
            name='licencia_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transportador',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transportador',
            name='email',
            field=models.EmailField(blank=True, max_length=150),
        ),
        migrations.AddIndex(
            model_name='transportador',
            index=models.Index(fields=['estado'], name='transportador_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='transportador',
            index=models.Index(fields=['nombre'], name='transportador_nombre_idx'),
        ),
        migrations.AddField(
            model_name='transportadorvehiculo',
            name='transportador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_vehiculo', to='transportadores.transportador'),
        ),
        migrations.AddField(
            model_name='transportadorvehiculo',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_transportador', to='transportadores.vehiculo'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='transportador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='transportadores.transportador'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='transportadores.vehiculo'),
        ),
        migrations.AddField(
            model_name='viajeremision',
            name='remision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_viaje', to='remisiones.remision'),
        ),
        migrations.AddField(
            model_name='viajeremision',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remisiones_asignadas', to='transportadores.viaje'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='remisiones',
            field=models.ManyToManyField(related_name='viajes', through='transportadores.ViajeRemision', to='remisiones.remision'),
        ),
        migrations.AddConstraint(
            model_name='transportadorvehiculo',
            constraint=models.UniqueConstraint(fields=('transportador', 'vehiculo'), name='transportador_vehiculo_unico'),
        ),
        migrations.AddIndex(
            model_name='viajeremision',
            index=models.Index(fields=['remision'], name='viaje_remision_remision_idx'),
        ),
        migrations.AddConstraint(
            model_name='viajeremision',
            constraint=models.UniqueConstraint(fields=('viaje', 'remision'), name='viaje_remision_unico'),
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['transportador'], name='viaje_transportador_idx'),
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['estado', 'fecha_salida'], name='viaje_estado_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['destino'], name='viaje_destino_idx'),
        ),
    ]
