# Generated by Django 6.1 on 2026-09-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remisiones", "0002_alter_remision_estado_and_more"),
        (
            "transportadores",
            "0002_transportadorvehiculo_vehiculo_viaje_viajeremision_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="viajeremision",
            constraint=models.UniqueConstraint(
                fields=("remision",), name="remision_unica_en_viaje"
            ),
        ),
    ]
