# Generated by Django 6.1 on 2026-09-11 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturas', '0001_initial'),
        ('remisiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='remision',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='remisiones.remision'),
        ),
    ]
