# Generated by Django 6.1 on 2026-09-13 22:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('facturas', '0002_initial'),
        ('productos', '0002_proveedor_productoproveedor_producto_proveedores_and_more'),
        ('remisiones', '0002_alter_remision_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=14)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'db_table': 'factura_detalles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FacturaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'factura_pagos',
                'ordering': ['-fecha_pago', '-id'],
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='factura',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factura',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EMITIDA', 'Emitida'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['cliente'], name='factura_cliente_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['fecha_emision'], name='factura_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['estado'], name='factura_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='factura',
            constraint=models.UniqueConstraint(condition=models.Q(('remision__isnull', False)), fields=('remision',), name='factura_remision_unica'),
        ),
        migrations.AddConstraint(
            model_name='factura',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='factura_subtotal_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='factura',
            constraint=models.CheckConstraint(condition=models.Q(('impuestos__gte', 0)), name='factura_impuestos_no_negativos'),
        ),
        migrations.AddConstraint(
            model_name='factura',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='factura_total_no_negativo'),
        ),
        migrations.AddField(
            model_name='facturadetalle',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturas.factura'),
        ),
        migrations.AddField(
            model_name='facturadetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_factura', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='facturapago',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='facturas.factura'),
        ),
        migrations.AddIndex(
            model_name='facturadetalle',
            index=models.Index(fields=['factura'], name='factura_detalle_factura_idx'),
        ),
        migrations.AddConstraint(
            model_name='facturadetalle',
            constraint=models.UniqueConstraint(fields=('factura', 'producto'), name='factura_producto_unico'),
        ),
        migrations.AddConstraint(
            model_name='facturadetalle',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='factura_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='facturadetalle',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='factura_precio_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='facturadetalle',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='factura_detalle_subtotal_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='facturapago',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='factura_pago_monto_positivo'),
        ),
    ]
