# Generated by Django 6.1 on 2026-09-14 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0002_remove_cotizacion_cotizacion_fecha_valida_and_more"),
        ("facturas", "0003_facturadetalle_facturapago_factura_actualizado_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="factura",
            name="cotizacion",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="factura",
                to="cotizaciones.cotizacion",
            ),
        ),
    ]
