# Generated by Django 6.1 on 2026-09-13 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('facturas', '0002_initial'),
        ('obras', '0001_initial'),
        ('productos', '0002_proveedor_productoproveedor_producto_proveedores_and_more'),
        ('transportadores', '0003_viajeremision_remision_unica_en_viaje'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('fecha_factura', models.DateField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('precio_transporte', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESADA', 'Procesada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('estado_factura', models.CharField(choices=[('SIN_FACTURA', 'Sin factura'), ('PENDIENTE', 'Pendiente'), ('GENERADA', 'Generada'), ('VENCIDA', 'Vencida')], default='SIN_FACTURA', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='facturas.factura')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='obras.obra')),
                ('transportador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='transportadores.transportador')),
            ],
            options={
                'db_table': 'devoluciones',
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DevolucionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=14)),
                ('peso_unitario', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('total_kg', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('motivo', models.CharField(choices=[('DEFECTUOSO', 'Defectuoso'), ('EXCESO_PEDIDO', 'Exceso de pedido'), ('CAMBIO_PRODUCTO', 'Cambio de producto'), ('OTRO', 'Otro')], max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='devoluciones.devolucion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_devolucion', to='productos.producto')),
            ],
            options={
                'db_table': 'devolucion_detalles',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='devolucion',
            index=models.Index(fields=['cliente'], name='devolucion_cliente_idx'),
        ),
        migrations.AddIndex(
            model_name='devolucion',
            index=models.Index(fields=['estado'], name='devolucion_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='devolucion',
            index=models.Index(fields=['estado_factura'], name='devolucion_factura_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='devolucion',
            constraint=models.CheckConstraint(condition=models.Q(('precio_transporte__gte', 0)), name='devolucion_transporte_no_negativo'),
        ),
        migrations.AddIndex(
            model_name='devoluciondetalle',
            index=models.Index(fields=['devolucion'], name='devolucion_detalle_dev_idx'),
        ),
        migrations.AddIndex(
            model_name='devoluciondetalle',
            index=models.Index(fields=['producto'], name='devolucion_detalle_prod_idx'),
        ),
        migrations.AddConstraint(
            model_name='devoluciondetalle',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='devolucion_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='devoluciondetalle',
            constraint=models.CheckConstraint(condition=models.Q(('peso_unitario__gte', 0)), name='devolucion_peso_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='devoluciondetalle',
            constraint=models.CheckConstraint(condition=models.Q(('total_kg__gte', 0)), name='devolucion_total_kg_no_negativo'),
        ),
    ]
